### ISSUE TITLE
identify where we can obtain the source code for mame4all

### ISSUE THREAD

**Issue by ginobean** [steward-fu/miyoo_rel#3]
Please identify the github repo, or other location, that contains the source code for the mame4all.dge executable binary.

Additionally, if there were any special steps/flags needed to build it for the BittBoy v.2 custom firmware, please itemize these as well, especially since it sounds like you are no longer involved with this project..

Thanks!

**Comment by steward-fu** [comment]
miyoo_src

**Comment by ginobean** [comment]
Thanks!
